os: linux
dist: xenial
language: node_js
node_js:
  - lts/*
cache: yarn
env:
  global:
  - WORKSPACE=$TRAVIS_BUILD_DIR
addons:
  apt:
    packages:
    - libgconf-2-4
branches:
    only:
      - master
name: "PSV Linux Build & Test"
script: $WORKSPACE/scripts/linux/psv/travis_build_test_psv.sh
deploy:
  - provider: script
    script: echo "Hello publish. Tag is $TRAVIS_TAG"
    cleanup: false
    on:
       branch: task/olpedge-1539-ci2
       condition: "$TRAVIS_TAG =~ ^testtag[0-9].[0-9].[0-9]$"
